bug(first_function): Fix unit tests when xray has been enabled
aws-samples/cookiecutter-aws-sam-python pull request #1
Opened 2018-04-26 09:13 UTC by Nr18

No issue available

*Description of changes:*
- Made sure that the xray components work/don't break during local execution or unit tests
- Enabled code coverage

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2018-04-26 12:22 UTC, heitorlessa requested changes
Minor style things

2018-04-26 12:22 UTC, heitorlessa commented on {{cookiecutter.project_slug}}/first_function/app.py
> +    if 'AWS_SAM_LOCAL' not in os.environ and 'LAMBDA_TASK_ROOT' in os.environ:
as we're calling this twice, perhaps make this as a method?

2018-04-26 12:22 UTC, heitorlessa commented on {{cookiecutter.project_slug}}/first_function/app.py
> +    if 'AWS_SAM_LOCAL' not in os.environ and 'LAMBDA_TASK_ROOT' in os.environ:
can we make this name more explicit?

2018-04-26 12:22 UTC, heitorlessa commented on {{cookiecutter.project_slug}}/first_function/app.py
> +        "body": json.dumps(my_function())
Would it be possible to use a variable instead of calling the function here? 

Something like: message = getMessage()...

2018-04-26 12:22 UTC, heitorlessa commented
Hey - Thank you so much for doing this - I loved it!

One minor change if you don't mind -- Although I like the "my function()" it's not prescriptive enough as in "getMessage" and calling them at the Body I don't particularly suggest that either, so if we can:

* Rename this to something more explicit
* Call this function inside the handler and assign the value to a variable
* Use that ret to body: <ret/message>
* **Perhaps** make that X-Ray check a method as we seem to be using in more than one place

Thoughts?

2018-04-26 12:54 UTC, Nr18 commented
Good feedback, I processed it in the new commits

2018-04-27 12:04 UTC, heitorlessa approved these changes

2018-04-27 12:05 UTC, merged